### ISSUE TITLE
Feedback on mini ex 7 by Joachim Demuth

### ISSUE THREAD

**Issue by joachimdemuth** [RikkeBadsberg/MiniEx#13]
Hi. 

First of all i kinda miss a description of your program because i can't really figure out which thoughts you put into this and what the meanings with it is. The program keeps showing error messages and im not sure whether its on purpose or not so that really confuses me. I get a feeling that something is missing. From what i can read off of your code some text is to be shown im just not sure if it is errors that are to be shown. So it would be nice with a description so i could be sure of what i am commenting on. 

Your code is super simple and well written. It is pretty easy for me to read, but it would be nice to see some comments from the author as well.

**Comment by RikkeBadsberg** [comment]
Thank you for feedback. I completely forgot the description, sorry. I added it moments ago, and I don't expect you to give another round of feedback based on that :) 
Well, I can tell you that I now have named it "Shapes (of Frustration)" and the errors was not intented to be the art part of this miniex ;)
