### ISSUE TITLE
Quick feedback on mini ex 7 by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [RikkeBadsberg/MiniEx#14]
Are you still working on this ex? (both in terms of code and README) I found some errors when I click on the button:

![screen shot 2017-03-27 at 3 04 33 pm](https://cloud.githubusercontent.com/assets/1446073/24357647/b6920e2c-12fe-11e7-802d-dfd97d0b7d55.png)

**Comment by RikkeBadsberg** [comment]
I wasn't really planning on working anymore on this - it isn't finished, but I don't know how to make it work.  Your screenshot shows a new error that I have not seen before. 
I made something simple previously, just a grid of buttons, I could upload that instead, but I'm kind of lost in the whole form art-thing.
