### ISSUE TITLE
Feedback on mini ex 7 by Jannik Ibsen

### ISSUE THREAD

**Issue by JannikIbsen** [RikkeBadsberg/MiniEx#15]
I don't wanna go over aspects brought up by Joachim, so instead i'll try to give some constructive feedback.
The code itself is structured and well executed, with the exception being your input function / CreateP.

I'm afraid i don't have alot of time on my hands at the moment, so i can't test whether my suggestion would work, but i'm 99% sure it would.

1:
Utilize the ".value" function.

(Example):

decision3 = createInput();
decision3.position(20, 500);
var answerdecision3= decision3.value();

2:
Now that you have the value of the input field defined, you can  utilize the array push function, at the moment you array is empty, with the "push" function, you can push values into the array, as seen here:

https://www.w3schools.com/jsref/jsref_push.asp

After this you can make a simple nested loop that runs through the array.length and for each itteration pushes a new textbox.

I'm not sure if this is what you've tried to accomplish as the Readme.MD is missing, but it's atleast one suggestion.

On a sidenote, don't get too frustrated, the p5.dom library does add another layer of complexity, so it can be hard to get a hold of at first.

**Comment by RikkeBadsberg** [comment]
Thank you for the constructive feedback! There is now a readme with a description and I think your solution would help achieving what I intented (though I was kind of confused about the art part of it and lacked a plan). I will try to find the time to test your solution - I want to figure out how this p5.dom library got me confused.
