### ISSUE TITLE
Feedback on mini_ex3 from Anine Hansen

### ISSUE THREAD

**Issue by a9neh** [RikkeBadsberg/MiniEx#3]
Hi.
This feedback is going to be in danish.
Jeg synes at det er en nice throbber som ikke er overkill. Jeg er vild med at der er forskellige shades istedet for bare én farve af gangen, og så kan den endda skifte farve og form!!!! Så sweet at den er interaktiv. Jeg har kun 2 kritikpunkter:
1. Når man trykker på en af piletasterne nok gange ryger throbberen ud af billedet. Det kunne være fedt hvis den kom ind på den anden side igen
2. Man skal hel klart have af vide at man kan interagere med den, ellers ved man det ikke. Så den kræver sådan en lille tekst som du selv skrev over den.
that's allll

Have fun don't die
//a9ne

**Comment by RikkeBadsberg** [comment]
Tak for feedback, og fedt med kritikpunkterne.
1. Jeg havde slet ikke tænkt over, at den selvfølgelig ryger ud over skærmen. God idé at den kommer ind på den anden side! (det kan være jeg prøver at lave det til næste miniex, hvis det giver mening med opgaven). 
2. Ja, det er nødvendigt med tekst, og det er på en måde lidt en skam, fordi det ikke giver mening sådan rigtigt med en throbber, synes jeg ikke. Lidt ligesom Googles ikke-internet dinosaurspil, hvor man ikke ved at det er et spil, med mindre man trykker på mellemrum (jeg fandt først ud af det til denne miniex, fordi en eller anden nævnte det :) )
